import { Job, Agent, Integration, ActivityEvent } from '@/types';

export const mockJobs: Job[] = [
  {
    id: '1',
    version: 1,
    generated_name: 'Fix authentication bug',
    generated_description: 'Fix authentication bug in OAuth callback',
    repo_id: 'getpullrequest/web',
    user_input: {
      source: 'gh-issues',
      prompt: 'Fix authentication bug',
    },
    status: 'in-progress',
    priority: 'high',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs:
      '[10:23:45] Starting job execution\n[10:23:47] Cloning repository\n[10:23:52] Analyzing codebase\n[10:24:15] Found potential issue in auth/oauth.ts',
    code_verification_logs: undefined,
    user_comments: undefined,
    confidence_score: '87',
    pr_link: undefined,
    user_acceptance_status: 'not_reviewed',
  },
  {
    id: '2',
    version: 1,
    generated_name: 'Add dark mode support',
    generated_description: 'Implement dark mode toggle and theme persistence',
    repo_id: 'getpullrequest/web',
    user_input: {
      source: 'gh-issues',
      prompt: 'Add dark mode support',
    },
    status: 'queued',
    priority: 'medium',
    order_in_queue: 1,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_comments: undefined,
    confidence_score: undefined,
    pr_link: undefined,
    user_acceptance_status: 'not_reviewed',
  },
  {
    id: '3',
    version: 1,
    generated_name: 'Optimize database queries',
    generated_description: 'Dashboard loading time is too slow',
    repo_id: 'getpullrequest/api',
    user_input: {
      source: 'slack',
      prompt: 'Optimize database queries',
    },
    status: 'queued',
    priority: 'high',
    order_in_queue: 2,
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_comments: undefined,
    confidence_score: undefined,
    pr_link: undefined,
    user_acceptance_status: 'not_reviewed',
  },
  {
    id: '4',
    version: 1,
    generated_name: 'Update dependencies',
    generated_description: 'Security updates for npm packages',
    repo_id: 'getpullrequest/web',
    user_input: {
      source: 'gh-issues',
      prompt: 'Update dependencies',
    },
    status: 'queued',
    priority: 'low',
    order_in_queue: 3,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date(Date.now() - 14400000).toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_comments: undefined,
    confidence_score: undefined,
    pr_link: undefined,
    user_acceptance_status: 'not_reviewed',
  },
  {
    id: '5',
    version: 1,
    generated_name: 'Fix mobile responsive layout',
    generated_description: 'Navigation menu breaks on mobile devices',
    repo_id: 'getpullrequest/web',
    user_input: {
      source: 'slack',
      prompt: 'Fix mobile responsive layout',
    },
    status: 'completed',
    priority: 'medium',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 18000000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_comments: undefined,
    pr_link: 'https://github.com/getpullrequest/web/pull/567',
    confidence_score: '92',
    user_acceptance_status: 'not_reviewed',
  },
  {
    id: '6',
    version: 1,
    generated_name: 'Add email notifications',
    generated_description: 'Send email when PR is ready for review',
    repo_id: 'getpullrequest/api',
    user_input: {
      source: 'gh-issues',
      prompt: 'Add email notifications',
    },
    status: 'completed',
    priority: 'medium',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 21600000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_comments: undefined,
    pr_link: 'https://github.com/getpullrequest/api/pull/890',
    confidence_score: '95',
    user_acceptance_status: 'not_reviewed',
  },
  {
    id: '7',
    version: 1,
    generated_name: 'Fix type errors in components',
    generated_description: 'TypeScript compilation errors in dashboard',
    repo_id: 'getpullrequest/web',
    user_input: {
      source: 'gh-issues',
      prompt: 'Fix type errors in components',
    },
    status: 'failed',
    priority: 'low',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 25200000).toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString(),
    created_by: 'system',
    updated_by: 'system',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_comments: undefined,
    confidence_score: undefined,
    pr_link: undefined,
    user_acceptance_status: 'not_reviewed',
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Sia Agent Alpha',
    status: 'active',
    config: {
      ip: '192.168.1.100',
      host: 'sia-agent-01.internal',
      port: 4001,
    },
    lastActive: new Date().toISOString(),
    recentActivity: [
      {
        id: 'act-1',
        action: 'Currently working on: Fix authentication bug',
        timestamp: new Date().toISOString(),
      },
      {
        id: 'act-2',
        action: 'Analyzing OAuth callback implementation',
        timestamp: new Date(Date.now() - 120000).toISOString(),
      },
      {
        id: 'act-3',
        action: 'Running security checks',
        timestamp: new Date(Date.now() - 300000).toISOString(),
      },
      {
        id: 'act-4',
        action: 'Code generation in progress',
        timestamp: new Date(Date.now() - 600000).toISOString(),
      },
    ],
  },
  {
    id: 'agent-2',
    name: 'Sia Agent 2',
    status: 'idle',
    config: {
      ip: '192.168.1.101',
      host: 'agent-02.internal',
      port: 8080,
    },
    lastActive: new Date(Date.now() - 120000).toISOString(),
    recentActivity: [
      {
        id: 'act-3',
        action: 'Completed job: Update dependencies',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
      },
    ],
  },
  {
    id: 'agent-3',
    name: 'Sia Agent 3',
    status: 'offline',
    config: {
      ip: '192.168.1.102',
      host: 'agent-03.internal',
      port: 8080,
    },
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    recentActivity: [],
  },
];

export const supportedIntegrations: Integration[] = [
  {
    id: 'github',
    name: 'GitHub',
    description:
      'Connect your GitHub repositories to automatically pull issues and create pull requests',
    status: 'disconnected',
    icon: 'github',
  },
  {
    id: 'linear',
    name: 'Linear',
    description:
      'Sync issues from Linear and track progress across your workflow',
    status: 'disconnected',
    icon: 'linear',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Get real-time notifications in your Discord channels',
    status: 'disconnected',
    icon: 'discord',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Receive updates and manage jobs directly from Slack',
    status: 'disconnected',
    icon: 'slack',
  },
  {
    id: 'cursor',
    name: 'Cursor Headless CLI',
    description: 'Connect Cursor to enable AI-powered code generation',
    status: 'disconnected',
    icon: 'cursor',
  },
  {
    id: 'claude-code',
    name: 'Claude Agent',
    description:
      'Integrate Claude Agent for advanced code generation capabilities',
    status: 'disconnected',
    icon: 'claude-code',
  },
  {
    id: 'kiro-cli',
    name: 'Kiro CLI',
    description: 'Connect Kiro CLI for command-line code generation',
    status: 'disconnected',
    icon: 'kiro-cli',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description:
      'Connect your GitLab repositories to automatically pull issues and create pull requests',
    status: 'disconnected',
    icon: 'gitlab',
  },
];

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: 'evt-1',
    type: 'pr_created',
    message: 'PR created for "Fix mobile responsive layout"',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    jobId: '5',
  },
  {
    id: 'evt-2',
    type: 'job_started',
    message: 'Started processing "Fix authentication bug"',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    jobId: '1',
  },
  {
    id: 'evt-3',
    type: 'job_completed',
    message: 'Completed "Add email notifications"',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    jobId: '6',
  },
  {
    id: 'evt-4',
    type: 'job_failed',
    message: 'Failed to process "Fix type errors in components"',
    timestamp: new Date(Date.now() - 2400000).toISOString(),
    jobId: '7',
  },
];
